name: 'Terraform'

on:
    push:
          branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
          inputs:
            action:
                description: "Choose action to execute"
                type: choice
                options:
                    - apply
                    - destroy

permissions:
    contents: read
    pull-requests: write
    id-token: write #

concurrency:
    group: terraform-state-lock
    cancel-in-progress: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production


    # use Bash shell regardless of platform 
    defaults:
        run:
          shell: bash
          working-directory: ./infrastructure
    
    steps:
        # checkout repo
    - name: Checkout
      uses: actions/checkout@v4


     # connect to Tailscale for Vault access
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} # uses GH sercrets
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci 

    # install Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3


    # fetch vault secrets
    - name: Import secrets from Vault
      uses: hashicorp/vault-action@v3
      with:
        # vault node info
        url: https://vault.waifuprotect.org
        method: "jwt"
        role: "github-actions"
        secrets: |
          secret/data/terraform/aws AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID ;
          secret/data/terraform/aws AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY

     # Initialize a new or existing hosting Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

        # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: github.event_name == 'push' || github.event_name == 'pull_request' || inputs.action == 'apply'
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' || inputs.action == 'apply'
      run: terraform apply -auto-approve -input=false

    # Destroy Job
    - name: Terraform Destroy Plan
      if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
      run: terraform plan -destroy

    - name: Terraform Destroy
      if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
      run: terraform destroy -auto-approve



